- id: '1595358403462'
  alias: Turn Living Room Desk Lamp on at sunset or 20:00
  description: ''
  trigger:
  - event: sunset
    offset: -00:20:00
    platform: sun
  - at: '20:00:00'
    platform: time
  condition:
  - after: '17:00:00'
    before: '21:00:00'
    condition: time
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.jp_iphone
      state: home
    - condition: state
      entity_id: device_tracker.iphonedeclaudia_3
      state: home
  action:
  - type: turn_on
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  mode: single
- id: '1595359336010'
  alias: Turn Living Room Desk Lamp off at 01:00
  description: ''
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  mode: single
- id: '1595547109688'
  alias: Turn Living Room Desk Lamp off if no one at home
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - after: '17:00:00'
    before: 00:00:00
    condition: time
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.jp_iphone
      state: Away
    - condition: state
      entity_id: device_tracker.iphonedeclaudia_3
      state: Away
  - condition: device
    type: is_on
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  action:
  - type: turn_off
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  mode: single
- id: '1600973987921'
  alias: Turn Living Room Desk Lamp on when we arrive
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.jp_iphone
      state: home
    - condition: state
      entity_id: device_tracker.iphonedeclaudia
      state: home
  - condition: time
    before: 00:00:00
    after: '17:00:00'
  - condition: device
    type: is_off
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  action:
  - type: turn_on
    device_id: 5999db1bf98f11eaa7fd15e95bbd9c0d
    entity_id: switch.shelly_living_room_desk_lamp
    domain: switch
  mode: single
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
- id: '1603977617607'
  alias: Turn Carol Lights on when blinds are closed
  description: ''
  trigger:
  - platform: device
    device_id: c3bc62def98f11ea956415a820dde960
    domain: cover
    entity_id: cover.shelly_carol_bedroom_blind
    type: closing
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.jp_iphone
      state: home
    - condition: state
      entity_id: device_tracker.iphonedeclaudia
      state: home
  action:
  - type: turn_on
    device_id: 58b805050d6b11ebb0f6098abda38308
    entity_id: switch.shelly_carol_room_lights
    domain: switch
  mode: single
- id: '1603977690271'
  alias: Turn Carol Lights off after the blinds are opened
  description: ''
  trigger:
  - platform: device
    device_id: c3bc62def98f11ea956415a820dde960
    domain: cover
    entity_id: cover.shelly_carol_bedroom_blind
    type: opening
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - type: turn_off
    device_id: 58b805050d6b11ebb0f6098abda38308
    entity_id: switch.shelly_carol_room_lights
    domain: switch
  mode: single
